Dockerfile
docker-compose.yml
provision-edx-exams.sh

The port value should be updated to a unique value. Followed the same format as https://github.com/edx/enterprise-access/commit/86b9fefe93497fb9d4501e87df2788c44fd2a77b to make this change.

fix: update port to unique value

---

edx_exams/settings/local.py
local-provision-edx-exams.sh

**JIRA:** https://2u-internal.atlassian.net/browse/MST-1533
**Description:** JWT/Oauth authentication was not working correctly for local dev environments. The following changes ensure that JWT authentication is successful. 

fix: ensure oauth is setup properly for local dev

---

.gitignore

**Description:** Updating .gitignore to include .vscode and reports/
-added .vscode which is VSCode's config file
-added reports/ which seems like autogenerated test output

chore: add files to .gitignore

---

edx_exams/apps/api/v1/tests/test_views.py
edx_exams/apps/api/v1/urls.py
edx_exams/apps/api/v1/views.py
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip.txt
requirements/production.txt
requirements/quality.txt
requirements/test.txt
requirements/validation.txt

**JIRA:** [WFDASH-1523](https://2u-internal.atlassian.net/browse/MST-1523)
**Description:** Creates an api endpoint that creates/updates course exam configs given the course ID and the proctoring provider.
instructions.
1. Open page A
2. Do thing B
4. If D happened instead - check failed.

add course exam config endpoint

---

edx_exams/apps/api/serializers.py
edx_exams/apps/api/v1/tests/test_views.py
edx_exams/apps/api/v1/urls.py
edx_exams/apps/api/v1/views.py

**JIRA:** [MST-1522](https://2u-internal.atlassian.net/browse/MST-1522)
**Description:** This adds a get endpoint to retrieve a list of all available proctoring providers

feat: adding get endpoint for proctoring providers

---

edx_exams/apps/core/admin.py

**JIRA:** [MST-1583](https://2u-internal.atlassian.net/browse/MST-1583)
**Description:** This PR makes all models visible in Django Admin.

feat: make models visible in django admin

---

docs/test_plan/exam_configuration.rst
docs/test_plan/readme.rst

**JIRA:** [MST-1657](https://2u-internal.atlassian.net/browse/MST-1657)
**Description:** Document testing steps for exam setup and provider configuration. (Dev milestone 2)
The plan is to have a separate file for each milestone/feature set to keep things organized. That is, assuming we choose to continue this approach in future milestones.

docs: testing plan for exam configuration

---

edx_exams/apps/core/admin.py
edx_exams/apps/core/models.py
edx_exams/apps/core/statuses.py
edx_exams/apps/core/tests/test_models.py

**JIRA:** https://2u-internal.atlassian.net/browse/MST-1731
- Fixes the blank labels, empty dropdowns, and infinite horizontal scrolling
- Added readonly to some fields that really shouldn't be updated in admin

feat: make django admin not terrible

---

edx_exams/apps/api/tests/test_utils.py
edx_exams/apps/api/utils.py
edx_exams/apps/api/v1/tests/test_views.py
edx_exams/apps/api/v1/urls.py
edx_exams/apps/api/v1/views.py
edx_exams/apps/core/constants.py
edx_exams/apps/core/models.py
edx_exams/settings/base.py
edx_exams/settings/local.py
edx_exams/settings/production.py
edx_exams/settings/test.py
requirements/base.in
requirements/base.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip.txt
requirements/production.txt
requirements/quality.txt
requirements/test.txt
requirements/validation.txt

**JIRA:** [MST-1598](https://2u-internal.atlassian.net/browse/MST-1598)
**Description:** This ticket adds a new http endpoint to edx-exams that gets exam access tickets.

feat: add exam access ticket endpoint

---

edx_exams/apps/api/v1/tests/test_views.py
edx_exams/apps/api/v1/urls.py
edx_exams/apps/api/v1/views.py
edx_exams/settings/base.py

**JIRA:** [MST-1783](https://2u-internal.atlassian.net/browse/MST-1783)
**Description:** This PR changes all occurrences of exam access ticket to exam access token.

fix: rename exam access ticket to token

---

edx_exams/apps/api/v1/tests/test_views.py
edx_exams/apps/api/v1/urls.py
edx_exams/apps/api/v1/views.py
edx_exams/apps/core/api.py
edx_exams/apps/core/models.py
edx_exams/apps/core/tests/test_api.py

**JIRA:** [Link to JIRA ticket](https://2u-internal.atlassian.net/browse/MST-1642)
**Description:** Adds a GET request endpoint for polling exam attempt data
**Author concerns:** Solution needs review
**Dependencies:** Might be impacted by MST-1653

feat: created basic GET exam attempt endpoint

---

docs/decisions/0003-token-exam-access.rst

**JIRA:** [MST-1535](https://2u-internal.atlassian.net/browse/MST-1535)
**Description:** Outlines ADR for gating exam access via JWT token.

docs: add ADR for token access

---

edx_exams/apps/api/v1/tests/test_views.py
edx_exams/apps/api/v1/views.py
edx_exams/apps/core/api.py
edx_exams/apps/core/tests/test_api.py

**JIRA:** [Link to JIRA ticket
](https://2u-internal.atlassian.net/browse/MST-1793)
**Description:** Added feature that sets an exam status to "submitted" on timeout
**Author concerns:** Tests need some work (see comment below)

feat: submit exam on timeout

---

edx_exams/apps/api/v1/urls.py
edx_exams/apps/api/v1/views.py
edx_exams/apps/router/interop.py
edx_exams/apps/router/middleware.py
edx_exams/apps/router/tests/test_interop.py
edx_exams/apps/router/tests/test_views.py
edx_exams/apps/router/views.py

**JIRA:** [MST-1856](https://2u-internal.atlassian.net/browse/MST-1856)
**Description:** Add middleware to support the proctoring settings endpoint. I also updated the name of the edx-exams view so that it is inline with other existing views.

feat: add middleware for provider settings

---

edx_exams/apps/api/v1/tests/test_views.py
edx_exams/apps/api/v1/views.py
edx_exams/apps/router/views.py

**JIRA:** [MST-1890](https://2u-internal.atlassian.net/browse/MST-1890)
**Description:** Add an endpoint to retrieve all active exams for a given course_id

feat: add endpoint to get course exams

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt
requirements/doc.txt
requirements/production.txt
requirements/quality.txt
requirements/test.txt
requirements/validation.txt

**JIRA:** [MST-1859](https://2u-internal.atlassian.net/browse/MST-1859)
**Description:** This PR upgrades lti-consumer-xblock so that the html message is updated based on the work [here in MST-1859](https://2u-internal.atlassian.net/browse/MST-1859)

chore: upgrade lti-consumer-xblock

---

requirements/base.txt
requirements/dev.txt
requirements/doc.txt
requirements/production.txt
requirements/quality.txt
requirements/test.txt
requirements/validation.txt

Updates lti-consumer to pull in https://github.com/openedx/xblock-lti-consumer/blob/master/CHANGELOG.rst#952---2023-05-24

feat: update lti-consumer

---

edx_exams/apps/lti/tests/test_views.py
edx_exams/apps/lti/views.py

**JIRA:** [MST-1899](https://2u-internal.atlassian.net/browse/MST-1899)
**Description:** Add context ID to LTI launch. This claim is required for Proctorio LTI launches.

feat: add context_id to LTI launch

---

edx_exams/apps/api/v1/tests/test_views.py
edx_exams/apps/api/v1/views.py

**JIRA:** [MST-1892](https://2u-internal.atlassian.net/browse/MST-1892)
**Description:** Adds DELETE to attempt API
**Author concerns:** Permissions still need to be altered to account for course staff roles

feat: delete attempt

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt
requirements/doc.txt
requirements/production.txt
requirements/quality.txt
requirements/test.txt
requirements/validation.txt

**JIRA:** Related to [MST-1932](https://2u-internal.atlassian.net/browse/MST-1932)
**Description:** Updates the version for xblock-lti-consumer to 9.5.3

chore: update xblock-lti-consumer version and dependencies

---

edx_exams/settings/base.py
edx_exams/settings/local.py

**JIRA:** Related to [MST-1942](https://2u-internal.atlassian.net/browse/MST-1942)
**Description:** Adding exams dashboard mfe url to cors whitelist (local only for now) for development.

feat: add exams dashboard to whitelist

---

docs/decisions/0004-downstream-effect-events.rst

**JIRA:** Link to JIRA ticket
**Description:** Describe in a couple of sentences what this PR adds
instructions.
1. Open page A
2. Do thing B
4. If D happened instead - check failed.

chore: set events adr approved

---

requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/pip.txt
requirements/production.txt
requirements/quality.txt
requirements/test.txt
requirements/validation.txt

Adding event-bus-redis for event producer & consumer implementation + local testing

chore: add event-bus-redis req

---

edx_exams/apps/core/signals/handlers.py
edx_exams/settings/base.py

**Description:** Events should be associated with a single topic. Producers have been updated to reflect this change, and I've created a new django setting for this name to make it easy to update in the future, if need be.

feat: update handler topics

---

edx_exams/apps/core/exam_types.py
edx_exams/apps/router/tests/test_views.py

**JIRA:** [COSMO-54](https://2u-internal.atlassian.net/browse/COSMO-54?atlOrigin=eyJpIjoiMzNmOWNhZGNkMGFjNDFiYmE1OGE4MzRhM2U1M2U2ZTgiLCJwIjoiaiJ9)
**Description:** Pairs with https://github.com/openedx/edx-platform/pull/33661. The change on this end doesn't have much impact just updating for consistency.

fix: practice exams are proctored

---

requirements/base.txt
requirements/ci.txt
requirements/common_constraints.txt
requirements/dev.txt
requirements/doc.txt
requirements/production.txt
requirements/quality.txt
requirements/test.txt
requirements/validation.txt

Updates the LTI consumer library to pull in: https://github.com/openedx/xblock-lti-consumer/pull/439

chore: update xblock-lti-consumer

---

requirements/base.txt
requirements/common_constraints.txt
requirements/dev.txt
requirements/doc.txt
requirements/production.txt
requirements/quality.txt
requirements/test.txt
requirements/validation.txt

Pulls in https://github.com/openedx/xblock-lti-consumer/pull/443

chore: update requirements

---

edx_exams/apps/core/middleware.py
edx_exams/settings/base.py
requirements/base.txt
requirements/ci.txt
requirements/common_constraints.txt
requirements/dev.txt
requirements/doc.txt
requirements/production.txt
requirements/quality.txt
requirements/test.txt
requirements/validation.txt

Reverts edx/edx-exams#244
The 5.10 release of edx-drf-extensions may have caused an auth issue https://github.com/openedx/edx-drf-extensions/blob/master/CHANGELOG.rst#1000---2023-11-30

Revert "Python Requirements Update"

---

.gitignore
edx_exams/settings/production.py
requirements/private.txt

Revert "Ilee2u/fix prod import django"

---

requirements/base.txt
requirements/ci.txt
requirements/common_constraints.txt
requirements/dev.txt
requirements/doc.txt
requirements/pip-tools.txt
requirements/pip.txt
requirements/production.txt
requirements/quality.txt
requirements/test.txt
requirements/validation.txt

Reverts edx/edx-exams#261
This might be causing errors with exams.

revert: "Python Requirements Update"

---

edx_exams/apps/api/v1/tests/test_views.py
edx_exams/apps/api/v1/views.py
edx_exams/apps/core/api.py
edx_exams/apps/core/models.py
edx_exams/apps/core/tests/test_api.py
edx_exams/apps/core/tests/test_models.py

**JIRA:** [COSMO-384](https://2u-internal.atlassian.net/browse/COSMO-384) [2U-internal] 
**Description:** Add any time allowances when calculating the exam timer or displaying the total exam time to the learner

feat: calculate exam time with allowances

---

edx_exams/settings/utils.py

**JIRA:** [Link to JIRA ticket
](https://2u-internal.atlassian.net/browse/COSMO-593)
**Description:** This PR modifies the logging configuration to align with the Datadog Python pipeline standards.
Adjusting logging format to ensure they are compatible with Datadog’s ingestion requirements.
Sets Django request logs to the INFO level to maintain optimal log verbosity and clarity.

chore: Refactor logging format for Datadog pipeline integration
