docs/decisions/0002-multiple-exam-systems.rst
Based on the discovery work at: https://2u-internal.atlassian.net/wiki/spaces/PT/pages/15438674/Discovery+Support+multiple+proctoring+subsystems
There's a list of each API call we currently make [here](https://2u-internal.atlassian.net/wiki/spaces/PT/pages/15439580/Technical+Reference+--+State+of+Proctoring#edx-proctoring-python-API). Although, by this solution edx-exams would only end up handling a subset of these.
=> docs: adr for brokering edx-proctoring calls

README.rst, requirements/dev.txt, requirements/pip-tools.txt
There is a bug in pip-tools 6.6.0 that prevents a pip-sync.
This PR bumps the version of pip-tools manually so users without the pip-tools fix will not experience an error when they first try to develop.
Tested on local after a virtualenvwrapper `wipeenv`.
=> chore: get local setup working

edx_exams/apps/core/views.py, edx_exams/settings/base.py, edx_exams/urls.py, requirements/base.in, requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip-tools.txt, requirements/production.txt, requirements/quality.txt, requirements/test.txt, requirements/validation.txt
Add api docs for edx-exams. In order for the health endpoint to be listed, I had to convert it to an API View. This might be a little hacky, so we could leave it as is and just have the API docs be empty for now.
=> feat: add API docs

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/upgrade-python-requirements.yml, Dockerfile
- Added a PR template for future pull requests
- Python requirements upgrade should target `main`, not `master`, as there is no `master` branch for this repository
- Docker publish action is failing right now because git is not installed. I looked at the edx-enterprise repository to mirror what's being done there to install requirements from github.
=> feat: add PR template and fix other github actions

edx_exams/apps/core/models.py
**JIRA:** [MST-1644](https://2u-internal.atlassian.net/browse/MST-1644)
**Description:** This PR drops the anonymous_user_id column for User model. Includes migration. Done as one release since there are no usages of the field. The re-adding of the anonymous_user_id as a UUIDField will be a separate PR/release.
=> feat: drop anonymous_user_id column for user

edx_exams/settings/production.py
**Description:** The sandbox config was overriding `EDX_DRF_EXTENSIONS`, which prevents user attributes from being correctly mapped from the JWT token. There is already a constant in the production settings file used to keep track of dictionary settings (so that only keys within the dictionary are updated, not the entire dictionary), so `EDX_DRF_EXTENSIONS` should be added to that constant.
=> fix: update dictionary settings list

edx_exams/apps/api/permissions.py, edx_exams/apps/api/v1/tests/test_views.py, edx_exams/apps/api/v1/views.py
**JIRA:** [MST-1527](https://2u-internal.atlassian.net/browse/MST-1527)
**Description:** GET course exam config. This is needed to fetch the currently selected provider in course-authoring.
=> feat: get endpoint for exam config

edx_exams/apps/lti/signals/handlers.py, edx_exams/apps/lti/views.py, requirements/base.in, requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip-tools.txt, requirements/pip.txt, requirements/production.txt, requirements/quality.txt, requirements/test.txt, requirements/validation.txt
**JIRA:** https://2u-internal.atlassian.net/browse/MST-1719
**Description:** This pulls in the old POC code with an additional commit to undo the migration applied by that branch that does not exist in master. Note this will temporarily break the LTI launch at runtime but the app otherwise still works as I had to comment out some imports that don't exist.
The problematic migration is here: [0015_add_remaining_fields_to_lti_config.py](https://github.com/openedx/xblock-lti-consumer/blob/zhancock/unmigrate/lti_consumer/migrations/0015_add_remaining_fields_to_lti_config.py)
The commit we're installing has a new migration to undo those DB changes: [0016_remove_lti_fields.py](https://github.com/openedx/xblock-lti-consumer/blob/zhancock/unmigrate/lti_consumer/migrations/0016_remove_lti_fields.py) …
=> feat: undo migration 'fork'

edx_exams/apps/lti/utils.py, edx_exams/apps/lti/views.py, edx_exams/settings/local.py
**JIRA:** [MST-1724](https://2u-internal.atlassian.net/browse/MST-1724?atlOrigin=eyJpIjoiNzliZTFjYjA1YzI1NGRlMTlhYThkODU2ZWI5YmY2NDgiLCJwIjoiaiJ9)
In order to make use of the edx browser JWT the client needs to explicitly request its use with a custom header. As a result, any redirect that occurs as part of the LTI launch flow cannot be authenticated using this JWT. This PR will create an explicit django session with the exam service when `/start_proctoring/` is called so those LTI callbacks will authenticate using the django session cookie. This is the one endpoint that can make use of the JWT since we expect this request to come from the learning MFE.
The downside for now is the initial request must come from the MFE and simply doing a GET request to …
=> feat: authenticate LTI exams launch

edx_exams/settings/base.py
Testing #59 in stage and found we lose the session in the final request of the flow. We need to accept the session cookie when the 'start assessment' button is hit inside the proctoring tool which is cross-site.
=> fix: allow cross-site session cookie for LTI launch

edx_exams/templates/admin/core/examattempt/change_form.html
**JIRA:** [MST-1735](https://2u-internal.atlassian.net/browse/MST-1735)
**Description:** Adds a button to launch the proctoring tool for an exam attempt in Django admin. This is a temporary measure to perform an LTI launch without the courseware frontend.
=> feat: add proctoring tool launch button

edx_exams/apps/core/admin.py, edx_exams/templates/admin/core/examattempt/change_form.html
Bug found while testing LTI launch on stage. The host url for this launch would end up being edx-exams-internal.edx.org which would cause the session cookie to get set on the internal domain. We want to launch to edx-exams.edx.org so any redirect from the tool (which would use edx-exams.edx.org) includes the session cookie.
=> fix: LTI link url should not be 'internal'

edx_exams/apps/core/middleware.py, edx_exams/settings/base.py
This may be a helpful fix as we build out browser endpoints in M3. Right now in order to test our JWT endpoints without a frontend it requires a browser extension like requestly to apply the USE_JWT_COOKIE_HEADER (example - https://app.requestly.io/rules/#sharedList/1671117948648-apply-edx-exams-jwt). This would make it so that header is implied if a JWT cookie is sent by the browser.
This is a bit jankey... but may be removed once we've completed the UI work.
=> feat: automatically use jwt auth

edx_exams/apps/api/v1/tests/test_views.py, edx_exams/apps/api/v1/urls.py, edx_exams/apps/api/v1/views.py, edx_exams/apps/core/api.py, edx_exams/apps/core/exceptions.py, edx_exams/apps/core/models.py, edx_exams/apps/core/tests/test_api.py
**JIRA:** [MST-1640](https://2u-internal.atlassian.net/browse/MST-1640)
**Description:** This PR adds support for an endpoint that allows exam attempt creation. The endpoint expects the following data 
`{ 
exam_id: <id>, 
start_clock: <Boolean>, 
}`
If the endpoint is called for a non-practice exam whose due date has passed, an exception is thrown. To mimic edx-proctoring behavior, attempts can be created for practice exams whose due date has passed.
=> feat: add endpoint to create exam attempt

README.rst
Make it easier to find the current exam setup instructions. This is a 2u internal link so these instructions eventually will need to move into the repo.
=> docs: add link to dev setup doc

edx_exams/settings/local.py
**JIRA:** n/a
**Description:** In order to be able to make calls to edx-exams in the frontend MFE locally, the url needs to be added to the cors whitelist in local.py.
=> feat: add learning mfe url to cors whitelist

edx_exams/apps/api/v1/tests/test_views.py, edx_exams/apps/api/v1/views.py, edx_exams/apps/core/constants.py, edx_exams/settings/base.py, edx_exams/settings/local.py
**JIRA:** [MST-1781](https://2u-internal.atlassian.net/browse/MST-1781)
**Description:** This PR moves the exam access token from a cookie to the response body. 
This PR addresses only the first criteria: 
Have the exam service return the token in the request body instead of a cookie.
- Include the expiration as an additional field. This can be used for UI performance improvements if needed later down the line.
=> feat: move exam access token to response body

edx_exams/apps/core/api.py, edx_exams/apps/core/models.py, edx_exams/apps/core/statuses.py, edx_exams/apps/core/tests/test_api.py
- Added functionality to models.py api.py to check that a user has no other active attempts when trying to start and exam attempt
- Refactored api.py code to compartmentalize the various if/else statements and such
**JIRA:** [Link to JIRA ticket](https://2u-internal.atlassian.net/browse/MST-1798)
**Description:** Only allow a user to start an exam if no other exam attempts are active.
=> feat: only one active attempt per user at a time

edx_exams/apps/api/v1/tests/test_views.py, edx_exams/apps/api/v1/views.py, edx_exams/apps/core/api.py, edx_exams/apps/core/tests/test_api.py, edx_exams/settings/local.py
**JIRA:** [MST-1797](https://2u-internal.atlassian.net/browse/MST-1797)
**Description:** This PR adds a few fixes for issues I found while testing my frontend changes for https://github.com/openedx/frontend-lib-special-exams/pull/88. 
I also included a settings update to allow devstack to communicate with the exams service. This same wildcard is found in `production.py` so there shouldn't be an issue with adding it to `local.py`. 
=> fix: bugs found for timed exams

edx_exams/apps/router/tests/test_views.py, edx_exams/apps/router/views.py
found a bug when testing against the UI. The legacy view pulls out the exam object and returns the exam as a dict when it should keep it wrapped in an 'exam' key.
current:
```
{
exam fields
}
```
fixed:
```
{
'exam': { exam fields }
}
```
=> fix: inconsistent exam response in legacy view

.gitignore
(This is a clean-up I noticed during the hackathon.)
The `.gitignore` file had cookiecutter placeholders (somehow?).  It makes "rg" complain when searching the repo:
```
% rg diff.cover
/System/Volumes/Data/root/src/edx/src/edx-exams/.gitignore: line 52: error parsing glob '{{cookiecutter.project_name}}/conf/locale/fake*/LC_MESSAGES/*.po': nested alternate groups are not allowed
/System/Volumes/Data/root/src/edx/src/edx-exams/.gitignore: line 53: error parsing glob '{{cookiecutter.project_name}}/conf/locale/fake*/LC_MESSAGES/*.mo': nested alternate groups are not allowed
/System/Volumes/Data/root/src/edx/src/edx-exams/.gitignore: line 54: error parsing glob '{{cookiecutter.project_name}}/conf/locale/messages.mo': nested alternate groups are not allowed
dev.in
6:diff-cover                # …
```
=> build: remove a vestigial cookiecutter artifact

edx_exams/apps/api/v1/tests/test_views.py, edx_exams/apps/api/v1/views.py
**JIRA:** [MST-1836](https://2u-internal.atlassian.net/browse/MST-1836)
**Description:** The frontend for exams expects a `total_time` field to be available for use in the entrance interstitials. Previously, this field had been left out of the backend so the interstitials did not appear as expected. 
=> feat: add total time to exam response

edx_exams/apps/lti/tests/test_views.py, edx_exams/apps/lti/urls.py, edx_exams/apps/lti/views.py
**JIRA:** [MST-1845](https://2u-internal.atlassian.net/browse/MST-1845)
This commits adds behavior to update a learner's exam attempt status to the "submitted" status when the learner ends their LTI proctoring assessment via the end_assessment view.
**Author concerns:**  None.
**Installation instructions:** Please follow the instructions in [Local Development and LTI Configuration](https://2u-internal.atlassian.net/wiki/spaces/PT/pages/256737327/Local+Development+and+LTI+Configuration) to set up your environment.
1. Create an `ExamAttempt` with the `created` status.
2. Go to `http://localhost:18740/lti/end_assessment/<attempt_id>`
3. Verify that the `ExamAttempt` has transitioned to the `submitted` state and that you see …
=> feat: update exam attempt status when in LTI end assessment launch

edx_exams/apps/api/serializers.py, edx_exams/apps/api/test_utils/factories.py, edx_exams/apps/api/v1/tests/test_views.py, edx_exams/apps/api/v1/urls.py, edx_exams/apps/api/v1/views.py, edx_exams/apps/core/api.py, edx_exams/settings/base.py
**JIRA:** [MST-1891](https://2u-internal.atlassian.net/browse/MST-1891)
**Description:** Adds a new endpoint to list attempts filtered by an exam id. This will drive the new 'instructor dashboard' component for exam. I expect this endpoint will include additional filter params beyond just exam_id once we add the search feature.
Using limit offset pagination allows the UI to decide it's own page size by setting the limit parameter.
Example `/instructor_view/attempts?exam_id=28&limit=20`
=> feat: add list attempt api

edx_exams/apps/api/v1/tests/test_views.py, edx_exams/apps/api/v1/views.py, edx_exams/apps/core/api.py, edx_exams/apps/core/tests/test_api.py
**JIRA:** [MST-1869](https://2u-internal.atlassian.net/browse/MST-1869)
The proctoring frontend hosted by the [frontend-lib-special-exams](https://github.com/openedx/frontend-lib-special-exams) frontend library is meant to block a learner from starting an exam that is passed due. The frontend relies on a key returned by the backend called `passed_due_date` to [determine whether or not to block access to the exam](https://github.com/openedx/frontend-lib-special-exams/blob/6b2ba0513624eb6e6fac00c38050edaf7c8a6ebe/src/helpers.js#L10C1-L16). The frontend calls `edx-exams's` `CourseExamAttemptView` GET endpoint to get information about the exam and the attempt, and it expects this key to be present in the response.
However, this key was missing, which allowed learners to …
=> fix: add passed_due_date key to response from CourseExamAttemptView GET endpoint

edx_exams/apps/lti/tests/test_views.py, edx_exams/apps/lti/views.py
**JIRA:** MST-1932
**Description:** This PR adds context (content url and MFE url as context_label and context_title respectively) to the launch data so that it can be used to redirect once an LTI proctored exam is started.
**Dependencies:** Blocked by https://github.com/openedx/xblock-lti-consumer/pull/382
=> feat: add context to launch data

edx_exams/apps/core/api.py, edx_exams/apps/lti/tests/test_views.py, edx_exams/apps/lti/urls.py, edx_exams/apps/lti/views.py
Creates a new view that will initiate a basic LTI 1.3 launch into the proctoring vendor's instructor tool. I opted to make this a view since returning the URL just adds an extra step to the UI to fetch it and stick it in an iframe. This way we just load up an iframe with `src=http://edx-exams.edx.org/lti/exam/28/instructor_tool` and this view does the rest.
Original concept was to build a generic launch view into the lti-consumer library based on this POC https://github.com/openedx/xblock-lti-consumer/pull/386. That PR documents the issues I found with that approach.
=> feat: launch instructor tool

Makefile
It's not clear what this was for, but it's probably not needed and doesn't seem like it would work anyhow. (And it's making `make requirements` fail.)
Part of https://github.com/edx/edx-arch-experiments/issues/391
=> build: Remove pycrypto system lib deletion hack

edx_exams/apps/lti/tests/test_views.py, edx_exams/apps/lti/views.py
**JIRA:** [MST-2099](https://2u-internal.atlassian.net/browse/MST-2099)
**Description:** Sets a return url for the proctoring tool when performing an LtiEndAssessment launch
Required so tool can properly redirect learner back after ending the assessment once https://github.com/openedx/frontend-lib-special-exams/pull/117 is implemented.
=> feat: exam end return url

edx_exams/settings/base.py, edx_exams/settings/devstack.py, edx_exams/settings/local.py, requirements/base.in, requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip-tools.txt, requirements/pip.txt, requirements/production.txt, requirements/quality.txt, requirements/test.txt, requirements/validation.txt
**JIRA:** None.
**Description:** This pull requests adds necessary configuration and packages to run the Kafka implementation of the Open edX event bus.
**Author concerns:** None.
None.
=> Set up Kafka Open edX event bus.

docs/decisions/0004-downstream-effect-events.rst
Corrected this ADR to align with the hackathon doc: https://2u-internal.atlassian.net/wiki/spaces/PT/pages/577699957/M6+Hackathon+Outline#Event-Signals%2C-Their-Data%2C-and-Destinations%3A
=> docs: downstream effect events corrected

edx_exams/apps/core/api.py, edx_exams/apps/core/apps.py, edx_exams/apps/core/signals/handlers.py, edx_exams/apps/core/signals/signals.py, edx_exams/apps/core/test_utils/factories.py, edx_exams/apps/core/tests/test_api.py, requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip-tools.txt, requirements/production.txt, requirements/quality.txt, requirements/test.txt, requirements/validation.txt
**JIRA:** [MST-2114](https://2u-internal.atlassian.net/browse/MST-2114) (private)
**Description:** This pull request introduces a change to emit the `TODO` Open edX event when a learner submits their exam.
**Author concerns:**  None.
**Dependencies:**
* https://github.com/openedx/openedx-events/pull/268
Follow the instructions in [How to start using the Event Bus](https://openedx.atlassian.net/wiki/spaces/AC/pages/3508699151/How+to+start+using+the+Event+Bus) to test out this event.
=> Emit the ExamAttemptSubmitted Open edX event when an exam is submitted.

edx_exams/apps/core/api.py, edx_exams/apps/core/signals/handlers.py, edx_exams/apps/core/signals/signals.py, edx_exams/apps/core/tests/test_api.py, edx_exams/apps/lti/signals/tests/test_handlers.py, edx_exams/apps/lti/tests/test_views.py
**JIRA:** [MST-2111](https://2u-internal.atlassian.net/browse/MST-2111)
**Description:** If an attempt's status is updated to verified, emit a verified event.
=> feat: emit verified event for attempt

edx_exams/apps/core/api.py, edx_exams/apps/core/signals/handlers.py, edx_exams/apps/core/signals/signals.py, edx_exams/apps/core/tests/test_api.py
**JIRA:** [MST-2108](https://2u-internal.atlassian.net/browse/MST-2108)
**Description:** If an exam attempt status is updated to `rejected` emit a signal.
=> feat: emit event for rejected exam attempt

.coveragerc, edx_exams/apps/core/api.py, edx_exams/apps/core/signals/handlers.py, edx_exams/apps/core/signals/signals.py, edx_exams/apps/core/tests/test_api.py
**JIRA:** [MST-2115](https://2u-internal.atlassian.net/browse/MST-2115)
**Description:** If an attempt's status is updated to `error`, emit an open edx event to be consumed by the event bus.
=> feat: emit error event

README.rst, docker-compose.yml
**JIRA:** None.
**Description:** This pull requests adds documentation for how to set up the Open edX event bus locally using devstack.
**Author concerns:** None.
**Testing instructions:** None.
=> Document developing on the devstack Open edX event bus.

edx_exams/settings/devstack.py, edx_exams/settings/local.py
**JIRA:** None.
**Description:**
This commit set Django settings in the local settings file for event bus networking settings to to `None`. These settings are used by the local application server. This change is necessary because the event bus does not work outside of a Docker container, because the event bus is run through the devstack networking layer, which is inaccessible by the local application server. Because the local settings file is also used by Tutor, only the networking related settings are set to `None`. The remaining settings are left as-is, because they are sensible defaults. Tutor uses can override these settings as need be.
**Author concerns:** None.
**Testing instructions:** None.
**Post …
=> Modify local Kafka settings.

edx_exams/apps/lti/views.py
**JIRA:** [MST-2159](https://2u-internal.atlassian.net/browse/MST-2159?atlOrigin=eyJpIjoiZjdkY2YzMThiMzhkNGNiNWFlMDhkYzY1M2ZhNzQ2NGYiLCJwIjoiaiJ9)
**Description:** The user_id passed to this function is used to lookup the initial launch data which is based on the user's database id instead of their external/anonymous id. 
**Author concerns:** Pretty sure this is the issue but hitting some problems with the IMS tools locally so I can't validate. Going to try this out on stage where things are working.
=> fix: end assessment launch

edx_exams/apps/core/api.py, edx_exams/apps/core/email.py, edx_exams/apps/core/templates/email/proctoring_attempt_rejected.html, edx_exams/apps/core/templates/email/proctoring_attempt_submitted.html, edx_exams/apps/core/templates/email/proctoring_attempt_verified.html, edx_exams/apps/core/tests/test_email.py, edx_exams/settings/base.py, edx_exams/settings/production.py, requirements/base.txt, requirements/ci.txt, requirements/common_constraints.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip.txt, requirements/production.in, requirements/production.txt, requirements/quality.txt, requirements/test.txt, requirements/validation.txt
**JIRA:** [MST-2087](https://2u-internal.atlassian.net/browse/MST-2087?atlOrigin=eyJpIjoiZGU3ODlhZDA5MTYyNDM3NzgxODE1YWU2Y2IzNjk1NDkiLCJwIjoiaiJ9)
**Description:** Send an email when a proctored exam is submitted/verified/rejected
**Author concerns:** I think this will "just work" since django-ses does all of the interfacing with AWS SES but we'll see.
=> feat: send proctoring update emails

edx_exams/apps/lti/tests/test_views.py, edx_exams/apps/lti/urls.py, edx_exams/apps/lti/views.py, edx_exams/settings/local.py, edx_exams/settings/test.py
**JIRA:** [COSMO-52](https://2u-internal.atlassian.net/browse/COSMO-52?atlOrigin=eyJpIjoiY2VhNTVjZGQzOGFmNGVkYzhiNTVhMTBhYTY3ZThmYmYiLCJwIjoiaiJ9)
**Description:** This is an experimental feature to test out an approach for passing a course roster to the Proctorio app. Long term it would be ideal that this app and any future apps use existing LTI endpoints such as the Names and Roles Provisioning endpoint to access this data. This one-off url is ultimately a shortcut to get us to releasable state faster.
Basically we make use of the same auth pattern we created for the start proctoring launch where we mint a new session token to be used in a third party UI flow since the correct headers to use default JWT auth won't be set. See #59
=> feat: roster endpoint POC

edx_exams/settings/base.py
**Description:**
Remove unused JWT_AUTH_REFRESH_COOKIE setting. This setting was never actually used, so there is no timing issues.
See DEPR for details:
https://github.com/openedx/public-engineering/issues/190
=> fix: remove JWT_AUTH_REFRESH_COOKIE

README.rst, docs/test_plan/proctored_exam.rst, docs/test_plan/readme.rst, docs/test_plan/timed_exam.rst
**JIRA:** Link to JIRA ticket
**Description:** Describe in a couple of sentences what this PR adds
instructions.
1. Open page A
2. Do thing B
4. If D happened instead - check failed.
=> docs: proctored exam testing instructions

edx_exams/apps/core/signals/signals.py, edx_exams/apps/core/tests/test_api.py
**JIRA:** [COSMO-82](https://2u-internal.atlassian.net/browse/COSMO-82)
**Description:** This was sending the database id from edx-exams. We should always be using lms_user_id when sending an user id to other systems.
=> fix: wrong user id sent to event bus

edx_exams/apps/lti/tests/test_views.py, edx_exams/apps/lti/views.py, edx_exams/settings/base.py, edx_exams/settings/local.py, edx_exams/settings/test.py
**JIRA:** [COSMO-126](https://2u-internal.atlassian.net/browse/COSMO-126?atlOrigin=eyJpIjoiOTBiNTIyMGZkZDQ3NDVlNmJkYzY2M2MzNzU5NjFhZWEiLCJwIjoiaiJ9)
**Description:**
Adds a `custom_url` parameter to the LTI launch. We'll use this to test a few possible approaches to using this url. More details in [COSMO-105](https://2u-internal.atlassian.net/browse/COSMO-105)
I've added an entirely new setting for this since that gives us maximum flexibility to play around in stage but I expect the end solution will be a bit more elegant and just use the existing MFE url setting.
=> feat: add custom domain param to LTI launch

edx_exams/apps/api/v1/tests/test_views.py, edx_exams/apps/api/v1/urls.py, edx_exams/apps/api/v1/views.py, edx_exams/apps/core/api.py, edx_exams/apps/core/data.py, edx_exams/apps/router/middleware.py, edx_exams/apps/router/tests/test_views.py, edx_exams/apps/router/views.py, requirements/base.in, requirements/base.txt, requirements/common_constraints.txt, requirements/dev.txt, requirements/doc.txt, requirements/quality.txt, requirements/validation.txt
**JIRA:** [COSMO-39](https://2u-internal.atlassian.net/browse/COSMO-39)
**Description:** This commit renames the `CourseProviderSettingsView` view to `ProctoringSettingsView` to accommodate additional settings beyond just provider settings; this more closely mirrors the purpose of the analogous `edx-proctoring` view. This commit also adds the escalation email to the response under the `proctoring_escalation_email` key. This changes allows the escalation email to appear in the error interstitial in the learning MFE.
**Screenshots:**
_Before:_
_After:_
**Author concerns:** None.
1. Set the `escalation_email` field on the `CourseExamConfiguration` model instance associated with the course in which you will …
=> feat: add escalation email to ProctoringSettingsView

edx_exams/apps/api/v1/urls.py, edx_exams/apps/core/constants.py
Fixes a bug where the existing regex would not match the entire content id into the capture group
This would break exams for any course with a `.` in the course id (and likely several other cases).
=> fix: not all usage keys matching

edx_exams/apps/core/admin.py, edx_exams/apps/lti/tests/test_views.py, edx_exams/apps/lti/utils.py, edx_exams/apps/lti/views.py, edx_exams/urls.py
**JIRA:** [COSMO-105](https://2u-internal.atlassian.net/browse/COSMO-105)
**Description:**
`custom_url` represents the url seen in the browser during an exam. When the extension is installed navigating to this URL will activate it and iframe in the exam content. By using a url we own we can handle what happens when the extension is not installed since the GET to /browser_lock will hit this service. If that happens we redirect the learner to getproctorio.com to install the extension.
The downside of this approach is getproctorio.com can't send the user back into the exam since we don't own that page. The learner would need to manually navigate back the the section and click start system check again.
To make this flow a bit smoother we would prefer learners download the extension first, …
=> feat: add proctorio redirect url

edx_exams/templates/proctorio_download.html
Confimed with Proctorio devs that so long as we return a valid HTML document this page will be hidden by the extension.
This is what the user would see briefly before the extension starts or if they do not have it installed:
=> feat: add full html page for proctorio launch

README.rst
=> chore: small readme typo, ls->lms

edx_exams/apps/core/admin.py
The default behavior of this field would be to put every row in the user table into the dropdown. That table is too big to render in a template, and worse, this could potentially lock up the database querying for every record.
=> fix: performance issue with coursestaffrole admin

requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/production.txt, requirements/quality.txt, requirements/test.txt, requirements/validation.txt
Will set the client.id to EVENTS_SERVICE_NAME (to be added in a separate PR)
=> feat: upgrade event bus kafka to allow for setting client ids when publishing/consuming events

edx_exams/apps/core/signals/handlers.py, edx_exams/apps/core/test_utils/factories.py, edx_exams/apps/core/tests/test_handlers.py
**JIRA:** https://2u-internal.atlassian.net/browse/COSMO-151 (2u-internal)
**Description:** Handles CourseAccessRole events that govern access to the exams dashboard and instructor API actions on exams.
Tested this against my local kafka event bus
=> feat: handle instructor permission events

edx_exams/apps/core/signals/handlers.py, edx_exams/settings/base.py, edx_exams/settings/devstack.py, edx_exams/settings/local.py
**JIRA:** [COSMO-205](https://2u-internal.atlassian.net/browse/COSMO-205)
**Description:** Now that openedx-events is above 8.6.0, events can be produced without using a secondary handler.
=> feat: add consumer config

edx_exams/apps/core/email.py, edx_exams/apps/core/templates/email/proctoring_attempt_rejected.html, edx_exams/apps/core/templates/email/proctoring_attempt_submitted.html, edx_exams/apps/core/templates/email/proctoring_attempt_verified.html
**JIRA:** 
[VAN-1833](https://2u-internal.atlassian.net/browse/VAN-1833)
Remove username and change subject in attempts emails 
It has been tested locally 
| Before  | After |
| ------------- | ------------- |
|  ![image](https://github.com/edx/edx-exams/assets/12580995/7452cae4-9310-457c-bd91-3c767a3f9e7c) | ![image](https://github.com/edx/edx-exams/assets/12580995/020e69c6-5cb1-47bb-bc3f-a093e3fff6dc)  |
|  ![image](https://github.com/edx/edx-exams/assets/12580995/2d7ae244-41c6-476c-9d54-9c9c37752d60) | ![image](https://github.com/edx/edx-exams/assets/12580995/222e69ad-39d4-473d-adfd-e627306ebeb0)|
=> fix: replace username with full name in attemp emails

edx_exams/apps/core/management/commands/bulk_add_course_staff.py, edx_exams/apps/core/management/commands/test/test_bulk_add_course_staff.py
**JIRA:** [Link to JIRA ticket](https://2u-internal.atlassian.net/browse/COSMO-236)
**Description:** When SRE tried to run the mgmt command in stage, there was an IntegrityError. After investigating, I realized there was a bug/missing edge case. This fix handles the case where there is a duplicate user in the csv itself (previously, was only checking if there was an existing User in the db)
**Author concerns:** Is this a case I should handle for duplicate CourseStaffRole entries in the CSV? I'm guessing no, because there shouldn't be duplicate entries when pulling from the db.
=> fix: handle dupe user case for mgmt cmd

edx_exams/apps/api/serializers.py, edx_exams/apps/api/v1/tests/test_views.py, edx_exams/apps/api/v1/urls.py, edx_exams/apps/api/v1/views.py, edx_exams/apps/core/admin.py, edx_exams/apps/core/models.py, edx_exams/apps/core/test_utils/factories.py
**JIRA:** [COSMO-368](https://2u-internal.atlassian.net/browse/COSMO-368)
**Description:** Adds API to retrieve a list of allowances by course id
The story suggested using generic DRF views for this since there's no business logic. I tried that out but found would introduce a new pattern without making it much simpler really. It would also mess with our class for exception logging
=> feat: GET allowances

.gitignore, edx_exams/apps/api/serializers.py, edx_exams/apps/api/v1/tests/test_views.py, edx_exams/apps/api/v1/views.py
**JIRA:** [COSMO-369](https://2u-internal.atlassian.net/browse/COSMO-369)
**Description:** This PR adds the ability to create one or more allowances via a POST request.
=> feat: add view for allowance creation

edx_exams/apps/core/management/commands/bulk_add_course_staff.py, edx_exams/apps/core/management/commands/test/test_bulk_add_course_staff.py
**JIRA:** [COSMO-234](https://2u-internal.atlassian.net/browse/COSMO-234)
**Description:** This PR updates the course staff role management command to use ignore_conflicts to handle duplicate/already existing users and course staff roles. This is more efficient, and more readable. I did do some research, test locally and find other usages to confirm that ignore_conflicts is supported in our environment.
=> fix: handle dupe course staff mgmt command

edx_exams/apps/api/v1/tests/test_views.py, edx_exams/apps/api/v1/urls.py, edx_exams/apps/api/v1/views.py, edx_exams/apps/core/constants.py
**JIRA:** [COSMO-395](https://2u-internal.atlassian.net/browse/COSMO-395) (2u-internal)
**Description:** Endpoint to delete allowances
Note I also added an authorization check to the post endpoint. We authorize the user against the course id passed into the view so we should only ever allow them to create/modify/delete allowances for exams in that course.
=> feat: delete allowance

edx_exams/apps/api/v1/tests/test_views.py, edx_exams/apps/api/v1/views.py
**JIRA:** [COSMO-418](https://2u-internal.atlassian.net/browse/COSMO-418)
**Description:** Fixes uncaught exception when a username/email is invalid.
=> fix: 500 error on invalid user

edx_exams/apps/core/management/commands/bulk_add_course_staff.py, edx_exams/apps/core/management/commands/test/test_bulk_add_course_staff.py
**JIRA:** [COSMO-234](https://2u-internal.atlassian.net/browse/COSMO-234)
**Description:** Attempting to fix the course staff role mgmt command by separating the loops and removing the atomic transaction. I am unable to replicate locally, but running this command in stage resulted in an error where the User couldn't be found.
=> fix: course staff mgmt command

edx_exams/settings/base.py
his repo is no longer using USE-JWT-COOKIE header, since it has the required edx-drf-extensions>10.2.0, where it was fully removed.
This is final clean-up for this repo.
See "[DEPR]: USE-JWT-COOKIE header" for more details:
- https://github.com/openedx/edx-drf-extensions/issues/371
**JIRA:** Link to JIRA ticket
**Description:** Describe in a couple of sentences what this PR adds
instructions.
1. Open page A
2. Do thing B
4. If D happened instead - check …
=> feat: DEPR USE-JWT-COOKIE header

edx_exams/settings/base.py
Reverts edx/edx-exams#312
A similar PR may have broken edx-platform, so reverting until investigation has completed. See https://github.com/openedx/edx-platform/pull/35397
=> Revert "feat: DEPR USE-JWT-COOKIE header"

edx_exams/apps/core/api.py, edx_exams/apps/core/tests/test_api.py
**JIRA:** [COSMO-469](https://2u-internal.atlassian.net/browse/COSMO-469?atlOrigin=eyJpIjoiNzY3ZTIyNTkzY2VkNDg0YWI3YTE2MzVmMzFmYTI3YjkiLCJwIjoiaiJ9)
**Description:** Fixes a bug where sending an exam status update with 'started' would always reset the exam start time allowing a user to gain additional time in their exam. This could be triggered in the UI by moving from the ready_to_submit page back to the exam.
=> fix: exam start time reset

edx_exams/apps/core/signals/handlers.py, edx_exams/apps/core/tests/test_handlers.py
**JIRA:** [COSMO-478](https://2u-internal.atlassian.net/browse/COSMO-478)
If a user is added to a course with either staff or instructor permissions, changes their email, and then is added to another course as staff or instructor, the second event meant to sync staff role permissions with edx-exams will fail due to an integrity/unique constraint error. This is because the call to get or create a new `User` object in the event handler is keyed off of both the `username` and `email` fields, which means that subsequent email changes will result in calls to create a new `User` object with the same `username` but new `email`, as opposed to just getting the existing `User` object. 
This bug is fixed by only using the `username` field to get or create a new `User` object. …
=> fix: allow course staff role to be updated with email change

edx_exams/settings/base.py
**JIRA:** [COSMO-462](https://2u-internal.atlassian.net/browse/COSMO-462)
**Description:** In order to have custom spans in datadog, we need to add `DeploymentMonitoringMiddleware` to the exams middleware.
=> fix: add middleware for datadog

edx_exams/settings/production.py
- PR created under the issue https://github.com/edx/edx-arch-experiments/issues/460
- Since we have upgraded to Django 4.2, we can remove the additional condition and variable.
=> Remove CSRF_TRUSTED_ORIGINS_WITH_SCHEMES variable

requirements/constraints.txt
Version 9.13.0 breaks LTI 1.3 launches. Until a new version of the package is released, the version needs to be pinned.
=> chore: pin lti version

requirements/constraints.txt
Version 9.13.1 contains a fix for LTI 1.3 launches, so this constraint should be removed.
=> chore: remove lti constraint

edx_exams/apps/api/v1/tests/test_views.py, edx_exams/apps/api/v1/urls.py, edx_exams/apps/api/v1/views.py, edx_exams/apps/router/interop.py, edx_exams/apps/router/middleware.py, edx_exams/apps/router/tests/test_interop.py, edx_exams/apps/router/tests/test_views.py, edx_exams/apps/router/views.py
**JIRA:** https://2u-internal.atlassian.net/browse/COSMO-623
**Description:** This PR adds support to route onboarding requests to the edx-proctoring backend via the edx-exams middleware. Because edx-exams does not support onboarding exams at this point, any requests routed to the edx-exams backend will return a 404 response.
=> feat: add middleware routing for onboarding endpoint

edx_exams/apps/router/interop.py, edx_exams/apps/router/tests/test_interop.py
Query and path parameters need to be re-encoded before being included in requests to the LMS.
=> fix: encode course id and username for lms request

edx_exams/apps/api/v1/tests/test_views.py, edx_exams/apps/api/v1/views.py
**JIRA:** [Link to JIRA ticket](https://2u-internal.atlassian.net/browse/CR-7304)
**Description:** Add a fix to allow course staff to view the exams they create, as currently some courses staff are blocked from viewing the exams they've created.
instructions.
1. Open page A
2. Do thing B
4. If D happened instead - check failed.
=> fix: grant course staff exam access tokens
